<?php

declare(strict_types=1);

namespace Semitexa\Update\Application\Service\Packaging\RemoteBootstrap\Support;

final class RemoteDeployEnvBuilder
{
    public function build(?string $remoteEnvFile, ?string $domain): string
    {
        $tempPath = $this->createTempFile();

        if ($remoteEnvFile !== null && trim($remoteEnvFile) !== '') {
            if (!is_file($remoteEnvFile) || !is_readable($remoteEnvFile)) {
                throw new \RuntimeException(sprintf(
                    'Remote env file "%s" does not exist or is not readable.',
                    $remoteEnvFile,
                ));
            }

            $content = file_get_contents($remoteEnvFile);
            if ($content === false) {
                throw new \RuntimeException(sprintf(
                    'Failed to read remote env file "%s".',
                    $remoteEnvFile,
                ));
            }

            $this->writeTempFile($tempPath, $content);

            return $tempPath;
        }

        $lines = [
            '# Generated by semitexa/update update:packages:bootstrap-remote',
            'APP_ENV=prod',
            'APP_DEBUG=0',
            'APP_SECRET=' . bin2hex(random_bytes(32)),
        ];

        if ($domain !== null && trim($domain) !== '') {
            $domain = trim($domain);
            if (preg_match('/[\r\n\0]/', $domain) === 1) {
                throw new \RuntimeException('Remote deploy domain must be a single-line host value.');
            }

            $lines[] = 'SEMITEXA_REMOTE_DEPLOY_DOMAIN=' . $domain;
        }

        $lines[] = '';

        $this->writeTempFile($tempPath, implode("\n", $lines));

        return $tempPath;
    }

    private function createTempFile(): string
    {
        $tempPath = tempnam(sys_get_temp_dir(), 'semitexa-remote-env-');
        if ($tempPath === false) {
            throw new \RuntimeException('Failed to create temporary remote env file.');
        }

        chmod($tempPath, 0600);

        return $tempPath;
    }

    private function writeTempFile(string $path, string $content): void
    {
        if (file_put_contents($path, $content, LOCK_EX) === false) {
            @unlink($path);
            throw new \RuntimeException('Failed to write temporary remote env file.');
        }

        chmod($path, 0600);
    }
}
